services:
  flask_app:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: aeyeweb
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nnUNet:/app/nnUNet
    command: gunicorn -c gunicorn.conf.py app:app  # for dev: command: flask run --host=0.0.0.0
    environment:
      FLASK_DEBUG: "0"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
  nginx:
    image: nginx:latest
    container_name: nginx_aeyeweb
    ports:
      - "80:80"
    depends_on:
      - flask_app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro