services:
  flask_app:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: aeyeweb
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nnUNet:/app/nnUNet
    environment:
      FLASK_DEBUG: "1"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia

